[package]
name = "solana-escrow"
version = "0.2.0"
edition = "2020"
license = "WTFPL"
publish = false

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.7.9"
spl-token = {version = "3.1.1", features = ["no-entrypoint"]}

[lib]
crate-type = ["cdylib", "lib"]
